version: "3.8"

services:
  wordpress:
    build: ./bin/wordpress
    container_name: 'wordpress_application'
    ports:
      - "${APPLICATION_OUTSIDE_HTTP_PORT}:80"
      - "${APPLICATION_OUTSIDE_SSL_PORT}:443"
    volumes:
      - ./../:/var/www/html
    networks:
      - wordpress
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
  mariadb:
    build: ./bin/mariadb/
    container_name: 'wordpress_mariadb'
    ports:
      - "${APPLICATION_OUTSIDE_MARIADB_PORT}:${MARIADB_PORT}"
    volumes:
      - ${MYSQL_DATABASE_FILES_PATH}:/var/lib/mysql
    environment:
      MARIADB_USER : ${WORDPRESS_DB_USER}
      MARIADB_PASSWORD : ${WORDPRESS_DB_PASSWORD}
      MARIADB_DATABASE: ${WORDPRESS_DB_NAME}
      MARIADB_RANDOM_ROOT_PASSWORD: ${MARIADB_RANDOM_ROOT_PASSWORD}
    networks:
      - wordpress
networks:
  wordpress:
